site_name: Docs
theme:
  name: material
  language: pt-BR
  features:
    - navigation.indexes     # ← habilita o clique na seção
    - navigation.instant
    - search.highlight
    - search.suggest
    - search.highlight
    - content.code.copy
  #logo: assets/logo.png
plugins:
  - search
nav:
  - Início: index.md
  - Financeiro:
  - TI:
